### PR TITLE
Colored Icons

### PR DESCRIPTION
**Pull request by REJack**
I've colorized the icons for any browser (Chrome, Firefox & Safari)
- Active = Blue
- Disabled = Grey
- Enabled = Green
- Unavailable = Red

I hope you like them 😁

### CODE REVIEW

**Comment by twolfson** [comment]
Looks good at a glance. Maybe we could keep "Disabled" as grey/black though? It feels like it would stand out when not in use =/

**Comment by REJack** [comment]
Good idea, I'll change this later.

**Comment by REJack** [comment]
Done 😃
I used the orignal files, it's funny Safari is black but Chrome & Firefox is grey, maybe we should change it to grey too.

**Comment by twolfson** [comment]
Hmm, I copy/pasted the Chrome images for the first revision. I guess we should verify that grey matches what Firefox is using for their icons

**Comment by REJack** [comment]
Done ^^

**Comment by twolfson** [comment]
Dope, thanks! I'll look into landing/releasing this by the end of the week

**Comment by REJack** [comment]
No problem, I can't wait for the release 😀

Have a nice week 😄

**Comment by twolfson** [comment]
Looking into landing this now. Just tried out the colored icons. They look great 💯

**Comment by twolfson** [comment]
This has been submitted to addons.mozilla.org. Hopefully it should be approved/released soon

It took a little longer than expected to submit as I wanted to automate the release process which is now done ✨

**Pull request merged**
